---
title: "Results Exploration"
author: "Robbie Howell"
date: "2026-01-08"
output: html_document
---

```{r setup, include=FALSE}
#This file reads in the raw result files and calculates the bias
knitr::opts_chunk$set(echo = TRUE)
library(Metrics)
library(ggplot2)
```


```{r}
#Currently reading in 50 rows at a time with 30 replicates each 
start_row = 1
end_row = 50
rows = 50
landscapes = 10
replicates = 30
cur_row = 1

#Calculates the bias for each individual replicate
bias_per_row = data.frame(matrix(NA, nrow=rows*replicates*landscapes, ncol=1))

for (i in start_row:end_row){
  #Prints progress every 10 rows, takes a while due to many replicates & landscapes per row
  if (i %% 10 == 0){
    print(paste("Row:", i))
  }
  
  for (j in 1:landscapes){
    
    for (k in 1:replicates){
      tryCatch({
        rm(output)
        #Change path to where your results are stored
        load(Sys.glob(paste0('~/Occupancy Research/30_replicate_results/first_50_results/occupancy-sampling-row-', i, '-landscape-', j, '-replicate-', k, '-20*.rda')))
      
        bias_per_row[cur_row, 1] = bias(output$psi.true, output$psi.est)
      }, error = function(e){
        message("Error: ", e$message)
        print(paste0("Row: ", i, "   Replicate: ", j))
        
        bias_per_row[cur_row, 1] = NA
      }) 
      cur_row = cur_row + 1
    }
    
  }
  
}

colnames(bias_per_row) = "bias"
#write.csv(bias_per_row, "bias_per_row_first_50_30_reps.csv", row.names=FALSE)
```






```{r}
#This calculates the average bias per set of replicates 
bias_per_combination = data.frame(matrix(NA, nrow=rows*landscapes, ncol=1))
colnames(bias_per_combination) = "bias"

cur_row = 1

for (i in 1:(rows*landscapes)){
  bias_sum = 0
    
  for (j in 1:replicates){
    bias_sum = bias_per_row$bias[cur_row] + bias_sum
    cur_row = cur_row + 1
  }
    
  bias_avg = bias_sum / replicates
  bias_per_combination$bias[i] = bias_avg
}

#write.csv(bias_per_combination, "bias_per_combination_first_50_30_reps.csv", row.names=FALSE)
```



```{r}
ggplot(bias_per_combination) + 
  aes(x=1:(rows*landscapes), y=bias) + 
  geom_point() + 
  scale_y_continuous(
    limits=c(-0.3, 0.1)
  )
```



