---
title: "test_results_figures"
author: "Robbie Howell"
date: "2026-01-09"
output: html_document
---

```{r setup, include=FALSE}
#This file combines the bias with the parameter dataframes and has some exploratory figures
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```


```{r}
bias_per_combination = read.csv("bias_per_combination_first_50_30_reps.csv")

landscapes = (1:10)
n.plots <- c(50, 100, 200, 400, 600)
design <- c("random", "grid", "h_line", "v_line", "box4", "box16", "heavy_pref", "mod_pref")
n_neighbors <- c(5, 10, 15, 20, 25)

#landscapes have to be expanded first to match the format of the results
parameters = expand.grid(landscapes=landscapes, n.plots = n.plots, design=design, n_neighbors=n_neighbors)

#Currently only using the first 500 rows of (10 landscapes for each set of parameters) since this is currently only looking at the first 50 parameter combinations
bias_with_parameters = parameters[1:500,]
bias_with_parameters$bias = bias_per_combination$bias


# Species prevalence
species_prev <- c(-1.734601, 0)
# Spatial decay
spatial_decay = c(3/.1, 3/.3, 3/.5, 3/.7, 3/.9)
landscape_comb <- expand.grid(prevalence = species_prev, decay = spatial_decay)

for (i in 1:nrow(bias_with_parameters)){
  bias_with_parameters$prevalence[i] = landscape_comb$prevalence[bias_with_parameters$landscapes[i]]
  bias_with_parameters$spatial_decay[i] = landscape_comb$decay[bias_with_parameters$landscapes[i]]
}
```




```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias) + 
  geom_point() + 
  scale_y_continuous(
    limits=c(-0.3, 0.1)
  )
```


```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias, color=factor(design)) + 
  geom_point() + 
  scale_y_continuous(
    limits=c(-0.3, 0.1)
  ) + 
  scale_color_viridis_d(option="plasma")
```



```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias) + 
  geom_point() + 
  facet_wrap(~n.plots) + 
  labs(
    title = "Number of Plots"
  )
```


```{r}
ggplot(bias_with_parameters) + 
  aes(y=bias) + 
  geom_boxplot() + 
  facet_wrap(~n.plots) + 
  labs(
    title = "Number of Plots"
  )
```




```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias) + 
  geom_point() + 
  facet_wrap(~design) + 
  labs(
    title = "Sampling Method"
  )
```

```{r}
ggplot(bias_with_parameters) + 
  aes(y=bias) + 
  geom_boxplot() + 
  facet_wrap(~design) + 
  labs(
    title = "Design"
  )
```




```{r}
print(paste0("16-Plot Boxes: ", mean(bias_with_parameters[bias_with_parameters$design == 'box16', ]$bias, na.rm=TRUE)))
print(paste0("4-Plot Boxes: ", mean(bias_with_parameters[bias_with_parameters$design == 'box4', ]$bias, na.rm=TRUE)))
print(paste0("Grid: ", mean(bias_with_parameters[bias_with_parameters$design == 'grid', ]$bias)))
print(paste0("Horizontal Lines: ", mean(bias_with_parameters[bias_with_parameters$design == 'h_line', ]$bias, na.rm=TRUE)))
print(paste0("Heavy Preferential: ", mean(bias_with_parameters[bias_with_parameters$design == 'heavy_pref', ]$bias)))
print(paste0("Moderate Preferential: ", mean(bias_with_parameters[bias_with_parameters$design == 'mod_pref', ]$bias, na.rm=TRUE)))
print(paste0("Random: ", mean(bias_with_parameters[bias_with_parameters$design == 'random', ]$bias)))
print(paste0("Vertical Lines: ", mean(bias_with_parameters[bias_with_parameters$design == 'v_line', ]$bias)))
```




```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias) + 
  geom_point() + 
  facet_wrap(~prevalence) + 
  labs(
    title = "Prevalence"
  )
```

```{r}
ggplot(bias_with_parameters) + 
  aes(y=bias) + 
  geom_boxplot() + 
  facet_wrap(~prevalence) + 
  labs(
    title = "Prevalence"
  )
```





```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias) + 
  geom_point() + 
  facet_wrap(~n_neighbors) + 
  labs(
    title = "N Neighbors"
  )
```

```{r}
ggplot(bias_with_parameters) + 
  aes(y=bias) + 
  geom_boxplot() + 
  facet_wrap(~n_neighbors) + 
  labs(
    title = "N Neighbors"
  )
```




```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias) + 
  geom_point() + 
  facet_wrap(~spatial_decay) + 
  labs(
    title = "Spatial Decay"
  )
```

```{r}
ggplot(bias_with_parameters) + 
  aes(y=bias) + 
  geom_boxplot() + 
  facet_wrap(~spatial_decay) + 
  labs(
    title = "Spatial Decay"
  )
```


```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias, color=factor(n_neighbors)) + 
  geom_point() + 
  facet_wrap(~n.plots) + 
  labs(
    title = "Number of Plots"
  ) + 
  scale_color_viridis_d(option="plasma")
```


```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias, color=factor(spatial_decay)) + 
  geom_point() + 
  facet_wrap(~n.plots) + 
  labs(
    title = "Number of Plots"
  ) + 
  scale_color_viridis_d(option="plasma")
```



```{r}
ggplot(bias_with_parameters) + 
  aes(x=bias) + 
  geom_density(fill="lightblue") + 
  facet_wrap(~n_neighbors) + 
  geom_vline(xintercept=0, color="red")
```

```{r}
ggplot(bias_with_parameters) + 
  aes(x=bias) + 
  geom_density(fill="lightblue") + 
  facet_wrap(~design) + 
  geom_vline(xintercept=0, color="red")
```



```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias, color=factor(spatial_decay)) + 
  geom_point() + 
  facet_wrap(~design) + 
  labs(
    title = "Design"
  ) + 
  scale_color_viridis_d(option="plasma")
```



```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias, color=factor(n_neighbors)) + 
  geom_point() + 
  facet_wrap(~design) + 
  labs(
    title = "Design"
  ) + 
  scale_color_viridis_d(option="plasma")
```



```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias, color=factor(n.plots), alpha=0.9) + 
  geom_point() + 
  facet_wrap(~design) + 
  labs(
    title = "Design"
  ) + 
  scale_color_viridis_d(option="plasma")
```



```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias, color=factor(design)) + 
  geom_point() + 
  facet_wrap(~n.plots) + 
  labs(
    title = "Number of Plots"
  ) + 
  scale_color_viridis_d(option="plasma")
```


```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias, color=factor(design)) + 
  geom_point() + 
  facet_wrap(~spatial_decay) + 
  labs(
    title = "Spatial Decay"
  ) + 
  scale_color_viridis_d(option="plasma")
```



```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias, color=factor(n.plots)) + 
  geom_point() + 
  facet_wrap(~design) + 
  labs(
    title = "Sampling Method"
  ) + 
  scale_color_viridis_d(option="plasma")
```



```{r}
ggplot(bias_with_parameters) + 
  aes(y=bias) + 
  geom_boxplot() + 
  facet_wrap(~landscapes) + 
  labs(
    title = "Landscape Type"
  )
```



```{r}
ggplot(bias_with_parameters) + 
  aes(x=1:nrow(bias_with_parameters), y=bias, color=factor(prevalence)) + 
  geom_point() + 
  facet_wrap(~design) + 
  labs(
    title = "Sampling Method"
  ) + 
  scale_color_viridis_d(option="plasma")
```



